# Generated by Codex on 2026-05-02

import django.core.validators
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybalance",
            name="location_ref",
            field=models.CharField(blank=True, default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventoryledgerentry",
            name="location_ref",
            field=models.CharField(blank=True, default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventoryledgerentry",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("inbound_receipt", "Ingreso por recepcion"),
                    ("reservation_hold", "Reserva"),
                    ("reservation_release", "Liberacion de reserva"),
                    ("pick", "Preparacion"),
                    ("dispatch", "Despacho"),
                    ("transfer_out", "Salida transferencia"),
                    ("transfer_in", "Entrada transferencia"),
                    ("adjustment", "Ajuste"),
                    ("transformation_in", "Transformacion entrada"),
                    ("transformation_out", "Transformacion salida"),
                    ("write_off", "Baja de inventario"),
                    ("reversal", "Reversa"),
                ],
                max_length=40,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="inventorybalance",
            name="uq_inventory_balance_bucket",
        ),
        migrations.AddConstraint(
            model_name="inventorybalance",
            constraint=models.UniqueConstraint(
                fields=("warehouse_ref", "location_ref", "item_ref", "lot_ref", "stock_state", "uom"),
                name="uq_inventory_balance_bucket",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybalance",
            index=models.Index(fields=["warehouse_ref", "location_ref", "item_ref"], name="inventory_i_warehou_6b5f3a_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryledgerentry",
            index=models.Index(fields=["warehouse_ref", "location_ref", "item_ref"], name="inventory_i_warehou_bd996b_idx"),
        ),
        migrations.CreateModel(
            name="InventoryWriteOff",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=120)),
                ("updated_by", models.CharField(blank=True, max_length=120)),
                ("source_system", models.CharField(default="litecore", max_length=40)),
                ("source_table", models.CharField(blank=True, max_length=120)),
                ("source_pk", models.CharField(blank=True, max_length=120)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                ("source_hash", models.CharField(blank=True, max_length=128)),
                ("legacy_transaction_number", models.CharField(blank=True, max_length=60)),
                ("legacy_sales_order_number", models.CharField(blank=True, max_length=60)),
                ("legacy_line_id", models.CharField(blank=True, max_length=60)),
                ("legacy_line_rec_id", models.CharField(blank=True, max_length=60)),
                ("legacy_rec_id", models.CharField(blank=True, max_length=60)),
                ("item_ref", models.CharField(blank=True, max_length=60)),
                ("warehouse_ref", models.CharField(blank=True, max_length=80)),
                ("store_ref", models.CharField(blank=True, max_length=80)),
                ("write_off_number", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("posted", "Posteada"),
                            ("reversed", "Reversada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("location_ref", models.CharField(blank=True, max_length=120)),
                ("target_location_ref", models.CharField(blank=True, max_length=120)),
                (
                    "source_stock_state",
                    models.CharField(
                        choices=[
                            ("on_hand", "Disponible fisico"),
                            ("reserved", "Reservado"),
                            ("picking", "En preparacion"),
                            ("packed", "Preparado"),
                            ("in_transit", "En transito"),
                            ("delivered", "Entregado"),
                            ("adjusted", "Ajustado"),
                            ("scrapped", "Merma"),
                            ("converted", "Convertido"),
                        ],
                        default="packed",
                        max_length=30,
                    ),
                ),
                ("reason_code", models.CharField(choices=[("breakage", "Rotura"), ("loss", "Perdida")], max_length=80)),
                ("reason", models.TextField()),
                ("requested_by", models.CharField(max_length=120)),
                ("approved_by", models.CharField(blank=True, max_length=120)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_by", models.CharField(blank=True, max_length=120)),
                ("reversal_reason", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["warehouse_ref", "status"], name="inventory_i_warehou_d0d01a_idx"),
                    models.Index(fields=["status", "created_at"], name="inventory_i_status_0a7d5e_idx"),
                    models.Index(fields=["write_off_number"], name="inventory_i_write_o_0f137c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryWriteOffLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=120)),
                ("updated_by", models.CharField(blank=True, max_length=120)),
                ("source_system", models.CharField(default="litecore", max_length=40)),
                ("source_table", models.CharField(blank=True, max_length=120)),
                ("source_pk", models.CharField(blank=True, max_length=120)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                ("source_hash", models.CharField(blank=True, max_length=128)),
                ("legacy_transaction_number", models.CharField(blank=True, max_length=60)),
                ("legacy_sales_order_number", models.CharField(blank=True, max_length=60)),
                ("legacy_line_id", models.CharField(blank=True, max_length=60)),
                ("legacy_line_rec_id", models.CharField(blank=True, max_length=60)),
                ("legacy_rec_id", models.CharField(blank=True, max_length=60)),
                ("item_ref", models.CharField(blank=True, max_length=60)),
                ("warehouse_ref", models.CharField(blank=True, max_length=80)),
                ("store_ref", models.CharField(blank=True, max_length=80)),
                ("line_number", models.PositiveIntegerField()),
                ("location_ref", models.CharField(blank=True, max_length=120)),
                ("target_location_ref", models.CharField(blank=True, max_length=120)),
                ("lot_ref", models.CharField(blank=True, max_length=80)),
                (
                    "stock_state",
                    models.CharField(
                        choices=[
                            ("on_hand", "Disponible fisico"),
                            ("reserved", "Reservado"),
                            ("picking", "En preparacion"),
                            ("packed", "Preparado"),
                            ("in_transit", "En transito"),
                            ("delivered", "Entregado"),
                            ("adjusted", "Ajustado"),
                            ("scrapped", "Merma"),
                            ("converted", "Convertido"),
                        ],
                        default="packed",
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ("posted_qty", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("uom", models.CharField(max_length=20)),
                ("reason_code", models.CharField(blank=True, max_length=80)),
                ("reason", models.TextField(blank=True)),
                (
                    "write_off",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.inventorywriteoff"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["item_ref", "warehouse_ref", "location_ref"], name="inventory_i_item_re_c43cab_idx"),
                    models.Index(fields=["stock_state", "warehouse_ref"], name="inventory_i_stock_s_723667_idx"),
                    models.Index(fields=["legacy_line_id"], name="inventory_i_legacy__15c23c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("write_off", "line_number"), name="uq_write_off_line_number"),
                ],
            },
        ),
    ]
