# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_locations_writeoffs"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryreservationline",
            name="source_location_ref",
            field=models.CharField(blank=True, default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventoryreservationline",
            name="location_ref",
            field=models.CharField(blank=True, default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Abierta"),
                    ("partially_allocated", "Parcialmente asignada"),
                    ("allocated", "Asignada"),
                    ("preparing", "En preparacion"),
                    ("released", "Liberada"),
                    ("consumed", "Consumida"),
                    ("expired", "Vencida"),
                    ("cancelled", "Cancelada"),
                ],
                default="open",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservationline",
            index=models.Index(fields=["warehouse_ref", "location_ref", "item_ref"], name="inventory_i_warehou_7827f3_idx"),
        ),
    ]
