# Generated by Django 5.2.6 on 2026-04-14 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('incident_number', models.CharField(max_length=40, unique=True)),
                ('domain', models.CharField(max_length=40)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('blocker', 'Bloqueante')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_review', 'En revision'), ('resolved', 'Resuelta'), ('cancelled', 'Cancelada')], default='open', max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['domain', 'status'], name='logistics_l_domain_7e9a52_idx'), models.Index(fields=['entity_type', 'entity_id'], name='logistics_l_entity__93dad2_idx'), models.Index(fields=['severity', 'created_at'], name='logistics_l_severit_eb90c4_idx')],
            },
        ),
    ]
