# Generated by Django 6.0.1 on 2026-04-27 02:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMasterSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('item_ref', models.CharField(max_length=60)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('sap_code', models.CharField(blank=True, max_length=80)),
                ('sap_item_id', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(blank=True, max_length=240)),
                ('long_name', models.CharField(blank=True, max_length=320)),
                ('category', models.CharField(blank=True, max_length=160)),
                ('coverage_group', models.CharField(blank=True, max_length=80)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('uom_code', models.CharField(blank=True, max_length=20)),
                ('raw_weight', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('weight_uom', models.CharField(blank=True, max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('raw_volume', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('volume_uom', models.CharField(blank=True, max_length=20)),
                ('volume_m3', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('multiple', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('freight_product', models.BooleanField(default=False)),
                ('source_file', models.CharField(blank=True, max_length=260)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['item_ref'], name='logistics_m_item_re_bd4751_idx'), models.Index(fields=['store_ref', 'item_ref'], name='logistics_m_store_r_4a9f73_idx'), models.Index(fields=['category'], name='logistics_m_categor_13271a_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_ref', 'item_ref'), name='uq_material_snapshot_store_item')],
            },
        ),
    ]
