# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_materialmastersnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialmastersnapshot",
            name="service_product",
            field=models.BooleanField(default=False),
        ),
    ]
