# Generated by Codex on 2026-05-02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_materialmastersnapshot_service_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseMaster",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=120)),
                ("updated_by", models.CharField(blank=True, max_length=120)),
                ("warehouse_ref", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("warehouse_type", models.CharField(blank=True, max_length=40)),
                ("branch_ref", models.CharField(blank=True, max_length=80)),
                ("store_ref", models.CharField(blank=True, max_length=80)),
                ("store_name", models.CharField(blank=True, max_length=160)),
                ("is_pickup_allowed", models.BooleanField(default=False)),
                ("is_shipping_allowed", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("default_available_location_ref", models.CharField(blank=True, max_length=120)),
                ("default_reserved_location_ref", models.CharField(blank=True, max_length=120)),
                ("default_preparation_location_ref", models.CharField(blank=True, max_length=120)),
                ("default_breakage_location_ref", models.CharField(blank=True, max_length=120)),
                ("default_loss_location_ref", models.CharField(blank=True, max_length=120)),
                ("source_system", models.CharField(default="tmswms", max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["active", "warehouse_ref"], name="logistics_w_active_6d3c05_idx"),
                    models.Index(fields=["store_ref", "active"], name="logistics_w_store_r_00e72c_idx"),
                    models.Index(fields=["branch_ref", "active"], name="logistics_w_branch__73210e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseLocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=120)),
                ("updated_by", models.CharField(blank=True, max_length=120)),
                ("warehouse_ref", models.CharField(max_length=80)),
                ("location_ref", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("location_type", models.CharField(max_length=40)),
                ("purpose", models.CharField(max_length=40)),
                ("zone_ref", models.CharField(blank=True, max_length=40)),
                ("aisle", models.CharField(blank=True, max_length=20)),
                ("floor", models.CharField(blank=True, max_length=20)),
                ("level", models.CharField(blank=True, max_length=20)),
                ("position", models.CharField(blank=True, max_length=20)),
                ("is_dispatchable", models.BooleanField(default=False)),
                ("is_reservable", models.BooleanField(default=False)),
                ("is_pickable", models.BooleanField(default=False)),
                ("allows_scrap", models.BooleanField(default=False)),
                ("system_location", models.BooleanField(default=False)),
                ("generated", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["warehouse_ref", "active"], name="logistics_w_warehou_16bc53_idx"),
                    models.Index(fields=["warehouse_ref", "purpose"], name="logistics_w_warehou_237f52_idx"),
                    models.Index(fields=["location_ref"], name="logistics_w_locatio_b41782_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("warehouse_ref", "location_ref"), name="uq_warehouse_location_ref"),
                ],
            },
        ),
    ]
