# Generated by Codex on 2026-05-02

from django.db import migrations, models


def _default_location_ref(warehouse_ref: str, suffix: str) -> str:
    return f"{str(warehouse_ref or '').strip().upper()}-{suffix}"


def ensure_transit_locations(apps, schema_editor):
    WarehouseMaster = apps.get_model("logistics", "WarehouseMaster")
    WarehouseLocation = apps.get_model("logistics", "WarehouseLocation")
    for warehouse in WarehouseMaster.objects.all().iterator():
        warehouse_ref = str(warehouse.warehouse_ref or "").strip().upper()
        if not warehouse_ref:
            continue
        transit_ref = _default_location_ref(warehouse_ref, "TRN-GEN")
        if not warehouse.default_transit_location_ref:
            warehouse.default_transit_location_ref = transit_ref
            warehouse.save(update_fields=["default_transit_location_ref", "updated_at"])
        WarehouseLocation.objects.update_or_create(
            warehouse_ref=warehouse_ref,
            location_ref=transit_ref,
            defaults={
                "name": "Transito / carga",
                "location_type": "system",
                "purpose": "transit",
                "zone_ref": "TRN",
                "aisle": "",
                "floor": "",
                "level": "",
                "position": "",
                "is_dispatchable": False,
                "is_reservable": False,
                "is_pickable": False,
                "allows_scrap": False,
                "system_location": True,
                "generated": True,
                "active": True,
                "sort_order": 40,
                "payload": {},
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_warehousemaster_warehouselocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousemaster",
            name="default_transit_location_ref",
            field=models.CharField(blank=True, default="", max_length=120),
            preserve_default=False,
        ),
        migrations.RunPython(ensure_transit_locations, migrations.RunPython.noop),
    ]
