const statusLabels: Record<string, string> = {
  action: "Accion",
  adjusted: "Ajustado",
  adjustment: "Ajuste",
  adjustment_pending_approval: "Ajuste pendiente",
  allocated: "Asignada",
  approved: "Aprobada",
  arrived: "Arribada",
  assigned: "Asignada",
  attempted: "Intentada",
  available: "Disponible",
  blocked: "Bloqueado",
  blocker: "Bloqueante",
  cancelled: "Cancelada",
  capacity_checked: "Capacidad validada",
  closed: "Cerrado",
  closed_with_incident: "Cerrado con incidencia",
  completed: "Completado",
  confirmed: "Confirmada",
  consumed: "Consumida",
  converted: "Convertido",
  counted: "Contada",
  counting: "En conteo",
  created: "Creada",
  critical: "Critico",
  customer_absent: "Cliente ausente",
  decrease: "Decrementa",
  delivered: "Entregada",
  delivered_complete: "Entregada completa",
  delivered_partial: "Entregada parcial",
  discrepant: "Con diferencia",
  discrepancy_review: "Revision de diferencias",
  dispatched: "Despachada",
  draft: "Borrador",
  en_route: "En ruta",
  error: "Error",
  expected: "Esperada",
  expired: "Vencida",
  failed: "Fallida",
  fallback_insufficient_points: "Ruteo manual: puntos insuficientes",
  fallback_no_ors_key: "Ruteo manual: sin clave ORS",
  fallback_ors_unavailable: "Ruteo manual: ORS no disponible",
  high: "Alta",
  in_review: "En revision",
  in_route: "En ruta",
  in_transit: "En transito",
  inactive: "Inactivo",
  increase: "Incrementa",
  insufficient: "Insuficiente",
  issue: "Incidencia",
  issued: "Emitido",
  loaded: "Cargada",
  loading: "En carga",
  logistics_issue: "Problema logistico",
  low: "Baja",
  maintenance: "Mantenimiento",
  medium: "Media",
  not_delivered: "No entregada",
  ok: "OK",
  on_hand: "Disponible fisico",
  offline: "Sin conexion",
  online: "En linea",
  open: "Abierto",
  out_of_service: "Fuera de servicio",
  packed: "Preparado",
  partial: "Parcial",
  partial_received: "Recibida parcial",
  partially_allocated: "Parcialmente asignada",
  partially_delivered: "Entregada parcial",
  pending: "Pendiente",
  pick: "Preparacion",
  picking: "Picking origen",
  planned: "Planificada",
  posted: "Posteada",
  prepared: "Preparada",
  preparing: "En preparacion",
  published: "Publicado",
  ready_for_dispatch: "Lista para despacho",
  received: "Recibida",
  receiving: "En recepcion",
  rejected: "Rechazo",
  released: "Liberada",
  remito: "Remito generado",
  reserved: "Reservada",
  rescheduled: "Reprogramada",
  resolved: "Resuelta",
  retired: "Baja",
  returned: "Devuelta",
  reversed: "Reversada",
  scrapped: "Merma",
  settlement_pending: "Rendicion pendiente",
  started: "Iniciada",
  succeeded: "Correcta",
  success: "Exito",
  suspended: "Suspendido",
  validated: "Validada",
  voided: "Anulado",
  warning: "Advertencia",
  with_incident: "Con incidencia",
};

function statusKey(value: string) {
  return value.trim().toLowerCase().replace(/[\s-]+/g, "_");
}

export function translateStatusLabel(value: string | null | undefined, fallback = "-") {
  const label = value?.trim();
  if (!label) {
    return fallback;
  }
  return statusLabels[statusKey(label)] ?? label;
}
