# Generated by Django 5.2.6 on 2026-04-14 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('dispatch_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('authorized', 'Autorizado'), ('prepared', 'Preparado'), ('counter_ready', 'En mostrador'), ('partial_pickup', 'Retiro parcial'), ('picked_up', 'Retirado'), ('with_incident', 'Con incidencia'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='requested', max_length=30)),
                ('customer_ref', models.CharField(max_length=80)),
                ('pickup_by_third_party', models.BooleanField(default=False)),
                ('third_party_snapshot', models.JSONField(blank=True, default=dict)),
                ('validation_payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'warehouse_ref'], name='dispatch_st_status_2a9c07_idx'), models.Index(fields=['customer_ref'], name='dispatch_st_custome_8085b7_idx'), models.Index(fields=['legacy_sales_order_number'], name='dispatch_st_legacy__0eb1ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreDispatchLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('picked_up_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('uom', models.CharField(max_length=20)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dispatch.storedispatch')),
            ],
            options={
                'indexes': [models.Index(fields=['item_ref', 'warehouse_ref'], name='dispatch_st_item_re_a982ae_idx'), models.Index(fields=['legacy_line_id'], name='dispatch_st_legacy__8e98fc_idx')],
            },
        ),
    ]
