# Generated by Django 5.2.6 on 2026-04-14 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('source_references', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditt_entity__55127c_idx'), models.Index(fields=['action', 'created_at'], name='core_auditt_action_eaca9b_idx'), models.Index(fields=['correlation_id'], name='core_auditt_correla_bb27e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainEventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('event_type', models.CharField(max_length=120)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_domain_status_10d261_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='core_domain_aggrega_672d40_idx'), models.Index(fields=['event_type', 'created_at'], name='core_domain_event_t_726a48_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('operation_type', models.CharField(max_length=80)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.CharField(blank=True, max_length=80)),
                ('request_hash', models.CharField(max_length=128)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['operation_type', 'reference_type', 'reference_id'], name='core_idempo_operati_e5eb34_idx'), models.Index(fields=['status', 'created_at'], name='core_idempo_status_7dae7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(max_length=40)),
                ('actor', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='core_status_entity__f7e35f_idx'), models.Index(fields=['to_status', 'created_at'], name='core_status_to_stat_b24ff5_idx')],
            },
        ),
    ]
