# Generated by Django 6.0.1 on 2026-04-24 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_delivery_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('created', 'Creada'), ('confirmed', 'Confirmada'), ('planned', 'Planificada'), ('assigned', 'Asignada'), ('preparing', 'En preparacion'), ('prepared', 'Preparada'), ('loaded', 'Cargada'), ('in_route', 'En ruta'), ('attempted', 'Intentada'), ('delivered_partial', 'Entregada parcial'), ('delivered_complete', 'Entregada total'), ('returned', 'Devuelta'), ('cancelled', 'Cancelada')], default='created', max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryPreparationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('assigned', 'Asignada'), ('preparing', 'En preparacion'), ('prepared', 'Preparada'), ('cancelled', 'Cancelada')], default='assigned', max_length=30)),
                ('assigned_to', models.CharField(max_length=120)),
                ('assigned_at', models.DateTimeField()),
                ('prepared_by', models.CharField(blank=True, max_length=120)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_task', to='fulfillment.deliveryorder')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'assigned_to'], name='fulfillment_status_faad63_idx'), models.Index(fields=['warehouse_ref', 'status'], name='fulfillment_warehou_e14452_idx')],
            },
        ),
    ]
