# Generated by Django 5.2.6 on 2026-04-27 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_issued_remitos_to_closed(apps, schema_editor):
    DeliveryDocument = apps.get_model("fulfillment", "DeliveryDocument")
    DeliveryDocument.objects.filter(status="issued").update(status="closed")


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0006_delivery_operational_quantities'),
    ]

    operations = [
        migrations.RunPython(migrate_issued_remitos_to_closed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='deliverydocument',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado'), ('voided', 'Anulado')], default='open', max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('route_stop_ref', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('delivered_complete', 'Entregada completa'), ('delivered_partial', 'Entregada parcial'), ('not_delivered', 'No entregada')], max_length=40)),
                ('reason', models.CharField(blank=True, choices=[('', 'Sin motivo'), ('customer_absent', 'Cliente ausente'), ('rejected', 'Rechazo'), ('logistics_issue', 'Problema logistico'), ('other', 'Otro')], max_length=40)),
                ('delivered_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('returned_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('executed_at', models.DateTimeField()),
                ('observations', models.TextField(blank=True)),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='fulfillment.deliveryorder')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery', 'executed_at'], name='fulfillment_deliver_2d1fdf_idx'), models.Index(fields=['route_stop_ref'], name='fulfillment_route_s_2c6438_idx'), models.Index(fields=['status', 'executed_at'], name='fulfillment_status_6150f4_idx')],
            },
        ),
    ]
