# Generated by Django 5.2.8 on 2026-06-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0012_expedition_queue_lookup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentorder',
            name='customer_document',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='customer_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fulfillmentorderline',
            name='item_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='fulfillmentorder',
            index=models.Index(fields=['customer_document'], name='fulfillment_custome_b26125_idx'),
        ),
    ]
