# Generated by Django 5.2.6 on 2026-04-14 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('route_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('planned', 'Planificada'), ('capacity_checked', 'Capacidad validada'), ('assigned', 'Asignada'), ('loading', 'En carga'), ('in_transit', 'En transito'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=30)),
                ('branch_ref', models.CharField(max_length=80)),
                ('warehouse_ref', models.CharField(max_length=80)),
                ('planned_date', models.DateField()),
                ('planned_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('planned_volume_m3', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('loaded_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('loaded_volume_m3', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('planning_version', models.PositiveIntegerField(default=1)),
                ('generated_by', models.CharField(default='manual', max_length=40)),
                ('capacity_override_reason', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RouteOptimizationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('algorithm', models.CharField(default='v1_capacity_zone_sequence', max_length=80)),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(default=dict)),
                ('accepted', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='routes.routesheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('assigned_by', models.CharField(max_length=120)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='vehicles.vehicle')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='routes.routesheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('planned', 'Planificada'), ('allocated', 'Asignada'), ('loaded', 'Cargada'), ('en_route', 'En ruta'), ('arrived', 'Arribada'), ('delivered', 'Entregada'), ('failed', 'Fallida'), ('rescheduled', 'Reprogramada'), ('cancelled', 'Cancelada')], default='pending', max_length=30)),
                ('customer_ref', models.CharField(max_length=80)),
                ('address_snapshot', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('planned_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('planned_volume_m3', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('incident_ref', models.CharField(blank=True, max_length=80)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.routesheet')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStopLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('delivery_ref', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('uom', models.CharField(max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volume_m3', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('capacity_estimated', models.BooleanField(default=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='routes.routestop')),
            ],
        ),
        migrations.AddIndex(
            model_name='routesheet',
            index=models.Index(fields=['status', 'planned_date'], name='routes_rout_status_df9a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='routesheet',
            index=models.Index(fields=['branch_ref', 'warehouse_ref'], name='routes_rout_branch__048435_idx'),
        ),
        migrations.AddIndex(
            model_name='routesheet',
            index=models.Index(fields=['route_number'], name='routes_rout_route_n_6dd571_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['status', 'sequence'], name='routes_rout_status_07548f_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['customer_ref'], name='routes_rout_custome_698a80_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['legacy_sales_order_number'], name='routes_rout_legacy__eea3a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='uq_route_stop_sequence'),
        ),
        migrations.AddIndex(
            model_name='routestopline',
            index=models.Index(fields=['delivery_ref'], name='routes_rout_deliver_cf8d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='routestopline',
            index=models.Index(fields=['item_ref', 'warehouse_ref'], name='routes_rout_item_re_de5892_idx'),
        ),
    ]
