# Generated by Django 5.2.6 on 2026-04-27 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesheet',
            name='driver_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='preview_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='route_geometry',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='routing_provider',
            field=models.CharField(default='manual', max_length=40),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='routesheet',
            name='total_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routestop',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='outcome_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routestop',
            name='outcome_reason',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='routestop',
            name='outcome_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='routestop',
            name='planned_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='service_time_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='routestop',
            name='source_ref',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='routestop',
            name='source_type',
            field=models.CharField(default='delivery_order', max_length=80),
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop_type',
            field=models.CharField(choices=[('delivery', 'Entrega cliente'), ('transfer', 'Transferencia interna'), ('depot', 'Deposito')], default='delivery', max_length=30),
        ),
        migrations.AddField(
            model_name='routestop',
            name='time_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='time_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestopline',
            name='delivered_qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='routestopline',
            name='difference_qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='routestopline',
            name='returned_qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='routestopline',
            name='source_line_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='routesheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('planned', 'Planificada'), ('capacity_checked', 'Capacidad validada'), ('assigned', 'Asignada'), ('loading', 'En carga'), ('in_transit', 'En transito'), ('settlement_pending', 'Rendicion pendiente'), ('closed', 'Cerrada'), ('closed_with_incident', 'Cerrada con incidencia'), ('cancelled', 'Cancelada')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='customer_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='routestopline',
            name='delivery_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='RouteRendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('posted', 'Posteada'), ('voided', 'Anulada')], default='draft', max_length=30)),
                ('closed_by', models.CharField(blank=True, max_length=120)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('has_incidents', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='routes.routesheet')),
            ],
        ),
        migrations.CreateModel(
            name='RouteRenditionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('delivered_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('returned_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('difference_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('observations', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rendition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='routes.routerendition')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendition_lines', to='routes.routestop')),
            ],
        ),
        migrations.AddIndex(
            model_name='routerendition',
            index=models.Index(fields=['route', 'status'], name='routes_rout_route_i_9e904f_idx'),
        ),
        migrations.AddIndex(
            model_name='routerendition',
            index=models.Index(fields=['closed_at'], name='routes_rout_closed__0ea6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='routerenditionline',
            index=models.Index(fields=['rendition', 'status'], name='routes_rout_renditi_9f2441_idx'),
        ),
        migrations.AddIndex(
            model_name='routerenditionline',
            index=models.Index(fields=['stop'], name='routes_rout_stop_id_b9ff83_idx'),
        ),
    ]
