# Generated by Django 5.2.6 on 2026-04-14 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCapacityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('max_weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('max_volume_m3', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('plate', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('in_route', 'En ruta'), ('maintenance', 'Mantenimiento'), ('out_of_service', 'Fuera de servicio'), ('retired', 'Baja')], default='available', max_length=30)),
                ('branch_ref', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('capacity_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclecapacityprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'branch_ref'], name='vehicles_ve_status_508035_idx'), models.Index(fields=['active'], name='vehicles_ve_active_544892_idx')],
            },
        ),
    ]
