# Generated by Django 6.0.1 on 2026-04-27 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('document_number', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('license_number', models.CharField(blank=True, max_length=80)),
                ('license_category', models.CharField(blank=True, max_length=40)),
                ('license_expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Asignado'), ('in_route', 'En ruta'), ('suspended', 'Suspendido'), ('inactive', 'Inactivo')], default='available', max_length=30)),
                ('branch_ref', models.CharField(blank=True, max_length=80)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'branch_ref'], name='vehicles_dr_status_c85fa8_idx'), models.Index(fields=['warehouse_ref', 'active'], name='vehicles_dr_warehou_f66255_idx'), models.Index(fields=['document_number'], name='vehicles_dr_documen_45aca3_idx')],
            },
        ),
    ]
