# Generated by Django 5.2.6 on 2026-04-14 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('shipment_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('prepared', 'Preparado'), ('dispatched', 'Despachado'), ('in_transit', 'En transito'), ('attempted', 'Intento'), ('rescheduled', 'Reprogramado'), ('delivered', 'Entregado'), ('returned', 'Devuelto'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='pending', max_length=30)),
                ('delivery_ref', models.CharField(max_length=80)),
                ('route_ref', models.CharField(blank=True, max_length=80)),
                ('carrier_ref', models.CharField(blank=True, max_length=80)),
                ('tracking_ref', models.CharField(blank=True, max_length=120)),
                ('planned_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'planned_date'], name='shipping_sh_status_941f0a_idx'), models.Index(fields=['delivery_ref'], name='shipping_sh_deliver_ec56ab_idx'), models.Index(fields=['route_ref'], name='shipping_sh_route_r_8fdd4d_idx'), models.Index(fields=['legacy_sales_order_number'], name='shipping_sh_legacy__f9351b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=40)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'indexes': [models.Index(fields=['shipment', 'created_at'], name='shipping_sh_shipmen_b998c2_idx'), models.Index(fields=['event_type', 'created_at'], name='shipping_sh_event_t_dd13ba_idx')],
            },
        ),
    ]
