# Generated by Django 5.2.6 on 2026-04-14 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('audit_number', models.CharField(max_length=40, unique=True)),
                ('warehouse_ref', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('counting', 'En conteo'), ('counted', 'Contada'), ('discrepancy_review', 'Revision de diferencias'), ('adjustment_pending_approval', 'Ajuste pendiente'), ('approved', 'Aprobada'), ('posted', 'Posteada'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=40)),
                ('blind_count', models.BooleanField(default=False)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['warehouse_ref', 'status'], name='audits_ware_warehou_668f6a_idx'), models.Index(fields=['audit_number'], name='audits_ware_audit_n_7074da_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseAuditLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('expected_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('difference_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('uom', models.CharField(max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('adjustment_ref', models.CharField(blank=True, max_length=80)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='audits.warehouseaudit')),
            ],
            options={
                'indexes': [models.Index(fields=['item_ref', 'warehouse_ref'], name='audits_ware_item_re_0bc486_idx'), models.Index(fields=['requires_approval'], name='audits_ware_require_617caa_idx')],
            },
        ),
    ]
