# Generated by Django 5.2.6 on 2026-04-14 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('transfer_number', models.CharField(max_length=40, unique=True)),
                ('origin_warehouse_ref', models.CharField(max_length=80)),
                ('destination_warehouse_ref', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('approved', 'Aprobada'), ('picking', 'Picking origen'), ('dispatched', 'Despachada'), ('in_transit', 'En transito'), ('partial_received', 'Recepcion parcial'), ('received', 'Recibida'), ('discrepant', 'Con diferencia'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='requested', max_length=30)),
                ('requested_by', models.CharField(max_length=120)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='transfers_t_status_493861_idx'), models.Index(fields=['origin_warehouse_ref', 'destination_warehouse_ref'], name='transfers_t_origin__42c86a_idx'), models.Index(fields=['transfer_number'], name='transfers_t_transfe_6c7903_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransferReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('has_differences', models.BooleanField(default=False)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='transfers.transferorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('shipment_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(default='created', max_length=30)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='transfers.transferorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='litecore', max_length=40)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('source_pk', models.CharField(blank=True, max_length=120)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('legacy_transaction_number', models.CharField(blank=True, max_length=60)),
                ('legacy_sales_order_number', models.CharField(blank=True, max_length=60)),
                ('legacy_line_id', models.CharField(blank=True, max_length=60)),
                ('legacy_line_rec_id', models.CharField(blank=True, max_length=60)),
                ('legacy_rec_id', models.CharField(blank=True, max_length=60)),
                ('item_ref', models.CharField(blank=True, max_length=60)),
                ('warehouse_ref', models.CharField(blank=True, max_length=80)),
                ('store_ref', models.CharField(blank=True, max_length=80)),
                ('line_number', models.PositiveIntegerField()),
                ('requested_qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('shipped_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('received_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('difference_qty', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('uom', models.CharField(max_length=20)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfers.transferorder')),
            ],
            options={
                'indexes': [models.Index(fields=['item_ref', 'warehouse_ref'], name='transfers_t_item_re_940f4d_idx'), models.Index(fields=['legacy_line_id'], name='transfers_t_legacy__320362_idx')],
                'constraints': [models.UniqueConstraint(fields=('transfer', 'line_number'), name='uq_transfer_line_number')],
            },
        ),
    ]
